// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-web',
    appId: '1:123456789:web:demo',
    messagingSenderId: '123456789',
    projectId: 'bar-boss-demo',
    authDomain: 'bar-boss-demo.firebaseapp.com',
    storageBucket: 'bar-boss-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyrMvVH3OU5sXytcetHgsiXuti0Pz-yY',
    appId: '1:779191401505:android:a22435f1dc76a95d3e3760',
    messagingSenderId: '779191401505',
    projectId: 'bar-boss-mobile',
    storageBucket: 'bar-boss-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEOV29Gizf6FUos0ngB92KJvt0YKrT3Oo',
    appId: '1:779191401505:ios:e086dbc3989f9dc03e3760',
    messagingSenderId: '779191401505',
    projectId: 'bar-boss-mobile',
    storageBucket: 'bar-boss-mobile.firebasestorage.app',
    iosBundleId: 'com.example.barBossMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-macos',
    appId: '1:123456789:macos:demo',
    messagingSenderId: '123456789',
    projectId: 'bar-boss-demo',
    storageBucket: 'bar-boss-demo.appspot.com',
    iosBundleId: 'com.example.barBossMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-windows',
    appId: '1:123456789:windows:demo',
    messagingSenderId: '123456789',
    projectId: 'bar-boss-demo',
    storageBucket: 'bar-boss-demo.appspot.com',
  );
}